//actionTypes.js
export const SEARCH_WORD_REQUEST = 'SEARCH_WORD_REQUEST';
export const SEARCH_WORD_SUCCESS = 'SEARCH_WORD_SUCCESS';
export const SEARCH_WORD_FAILURE = 'SEARCH_WORD_FAILURE';

export const ADD_TO_HISTORY='ADD_TO_HISTORY';